const staffOverviewData = [
    {
        title: "All Applications",
        status: "4",
        color: "bg-green-300 text-gray-900",
        icon: <ScrollText className="w-5 h-5 text-slate-600" />,
        iconColor: "text-green-600",
    },
    {
        title: "New Applicants",
        status: "6",
        color: "bg-yellow-300 text-gray-900",
        icon: <Users className="w-5 h-5 text-slate-600" />,
        iconColor: "text-yellow-600",
    },
    {
        title: "Renewal Applicants",
        status: "6",
        color: "bg-blue-300 text-gray-900",
        icon: <Users className="w-5 h-5 text-slate-600" />,
        iconColor: "text-blue-600",
    },
    {
        title: "Approved Applications",
        status: "6",
        color: "bg-orange-300 text-gray-900",
        icon: <CheckCircle className="w-5 h-5 text-slate-600" />,
        iconColor: "text-orange-600",
    },
    {
        title: "Rejected Applications",
        status: "2",
        color: "bg-orange-300 text-gray-900",
        icon: <XCircleIcon className="w-5 h-5 text-slate-600" />,
        iconColor: "text-orange-600",
    },
    {
        title: "All Scholars",
        status: "100",
        color: "bg-orange-300 text-gray-900",
        icon: <Users className="w-5 h-5 text-slate-600" />,
        iconColor: "text-orange-600",
    },
    {
        title: "New Scholars",
        status: "40",
        color: "bg-orange-300 text-gray-900",
        icon: <Users className="w-5 h-5 text-slate-600" />,
        iconColor: "text-orange-600",
    },
    {
        title: "Old Scholars",
        status: "60",
        color: "bg-orange-300 text-gray-900",
        icon: <Users className="w-5 h-5 text-slate-600" />,
        iconColor: "text-orange-600",
    },
    {
        title: "Upcoming Events",
        status: "3",
        color: "bg-orange-300 text-gray-900",
        icon: <Calendar1 className="w-5 h-5 text-slate-600" />,
        iconColor: "text-orange-600",
    },
    {
        title: "New Community Services",
        status: "16",
        color: "bg-orange-300 text-gray-900",
        icon: <HandHeartIcon className="w-5 h-5 text-slate-600" />,
        iconColor: "text-orange-600",
    },
];