// import FORM_SECTIONS from "../application/formSections";

// const formConfig = {
//     [FORM_SECTIONS.APPLICATION]: [
//         {
//             name: "school_year",
//             label: "School Year",
//             type: "text",
//             required: true,
//         },
//         // { name: "caseNo", label: "Case Number", type: "text", required: true },
//     ],
//     [FORM_SECTIONS.PERSONAL]: [
//         { name: "last_name", label: "Last Name", type: "text", required: true },
//         {
//             name: "first_name",
//             label: "First Name",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "middle_name",
//             label: "Middle Name",
//             type: "text",
//             required: false,
//         },
//         {
//             name: "suffix",
//             label: "Suffix",
//             type: "select",
//             options: ["", "None", "Jr", "Sr", "I", "II", "III", "IV"],
//             defaultValue: "",
//             required: false,
//         },
//         {
//             name: "gender",
//             label: "Gender",
//             type: "select",
//             options: ["", "Male", "Female"],
//             defaultValue: "",
//             required: true,
//         },
//         { name: "age", label: "Age", type: "number", required: true },
//         {
//             name: "birthdate",
//             label: "Birthdate",
//             type: "date",
//             required: true,
//         },
//         {
//             name: "birthplace",
//             label: "Birthplace",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "home_address",
//             label: "Home Address",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "subdivision",
//             label: "Village/Subdivision",
//             type: "text",
//             required: false,
//         },
//         { name: "barangay", label: "Barangay", type: "text", required: true },
//         {
//             name: "city",
//             label: "City/Municipality",
//             type: "text",
//             required: true,
//         },
//         { name: "zip_code", label: "Zipcode", type: "text", required: true },
//         {
//             name: "contact_number",
//             label: "Personal Contact",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "secondary_contact",
//             label: "Secondary Contact",
//             type: "text",
//             required: false,
//         },
//         { name: "religion", label: "Religion", type: "text", required: true },
//         {
//             name: "civil_status",
//             label: "Civil Status",
//             type: "text",
//             required: true,
//         },
//         { name: "facebook", label: "Facebook", type: "text", required: true },
//         {
//             name: "email",
//             label: "Email Address",
//             type: "email",
//             required: true,
//         },
//     ],
//     [FORM_SECTIONS.EDUCATION]: [
//         {
//             name: "previous_school",
//             label: "Last School Attended",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "previous_location",
//             label: "Location",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "previous_honor",
//             label: "Honor Award",
//             type: "text",
//             required: false,
//         },
//         { name: "previous_gwa", label: "GWA", type: "text", required: true },
//         {
//             name: "previous_course",
//             label: "Track",
//             type: "text",
//             required: false,
//         },
//         {
//             name: "incoming_grade",
//             label: "Incoming Grade/Year Level",
//             type: "select",
//             options: ["Select", "JHS", "SHS", "College", "Vocational"],
//             defaultValue: "College",
//             required: true,
//         },
//         // {
//         //     name: "present_school",
//         //     label: "School",
//         //     type: "text",
//         //     required: true,
//         // },
//         {
//             name: "present_school",
//             label: "College/University",
//             type: "select",
//             options: [{ key: 0, name: "" }],
//             defaultValue: "",
//             required: true,
//         },
//         {
//             name: "present_location",
//             label: "Location",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "present_course1",
//             label: "Course 1",
//             type: "select",
//             options: [{ key: 0, name: "" }],
//             defaultValue: "",
//             required: true,
//         },
//         {
//             name: "present_course2",
//             label: "Course 2",
//             type: "select",
//             options: [{ key: 0, name: "" }],
//             defaultValue: "",
//             required: false,
//         },
//         {
//             name: "year_level",
//             label: "Year Level",
//             type: "select",
//             options: [
//                 { value: "", name: "" },
//                 { value: 2, name: "2nd Year" },
//                 { value: 3, name: "3rd Year" },
//                 { value: 4, name: "4th Year" },
//             ],
//             defaultValue: "",
//             required: true,
//         },
//     ],
//     [FORM_SECTIONS.FAMILY]: [
//         // Father's information
//         {
//             name: "father_name",
//             label: "Name of Father",
//             type: "text",
//             required: true,
//         },
//         { name: "father_age", label: "Age", type: "number", required: true },
//         {
//             name: "father_education",
//             label: "Educational Attainment",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "father_occupation",
//             label: "Occupation",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "father_income",
//             label: "Monthly Income",
//             type: "number",
//             required: true,
//         },
//         {
//             name: "father_contact",
//             label: "Contact Number",
//             type: "text",
//             required: true,
//         },

//         // Mother's information
//         {
//             name: "mother_name",
//             label: "Name of Mother",
//             type: "text",
//             required: true,
//         },
//         { name: "mother_age", label: "Age", type: "number", required: true },
//         {
//             name: "mother_education",
//             label: "Educational Attainment",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "mother_occupation",
//             label: "Occupation",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "mother_income",
//             label: "Monthly Income",
//             type: "number",
//             required: true,
//         },
//         {
//             name: "mother_contact",
//             label: "Contact Number",
//             type: "text",
//             required: true,
//         },

//         // Guardian's information
//         {
//             name: "guardian_name",
//             label: "Guardian Name",
//             type: "text",
//             required: false,
//         },
//         { name: "guardian_age", label: "Age", type: "text", required: false },
//         {
//             name: "guardian_education",
//             label: "Educational Attainment",
//             type: "text",
//             required: false,
//         },
//         {
//             name: "guardian_occupation",
//             label: "Occupation",
//             type: "text",
//             required: false,
//         },
//         {
//             name: "guardian_income",
//             label: "Monthly Income",
//             type: "text",
//             required: false,
//         },
//         {
//             name: "guardian_contact",
//             label: "Contact Number",
//             type: "text",
//             required: false,
//         },
//     ],
//     [FORM_SECTIONS.CONTACT_PERSON]: [
//         {
//             name: "emergency_contact_name",
//             label: "Name",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "emergency_contact_relationship",
//             label: "Relationship",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "emergency_contact_address",
//             label: "Address",
//             type: "text",
//             required: true,
//         },
//         {
//             name: "emergency_contact_number",
//             label: "Contact Number",
//             type: "text",
//             required: true,
//         },
//     ],
//     [FORM_SECTIONS.OTHER_INFORMATION]: [
//         {
//             name: "expectation",
//             label: "What is your expectation from Tzu Chi Foundation?",
//             type: "textarea",
//             required: true,
//         },
//     ],
// };

// export default formConfig;

import FORM_SECTIONS from "../application/formSections";

const formConfig = {
    [FORM_SECTIONS.APPLICATION]: [
        {
            name: "school_year",
            label: "School Year",
            type: "text",
            required: true,
            placeholder: "e.g., 2024-2025",
        },
        // { name: "caseNo", label: "Case Number", type: "text", required: true },
    ],
    [FORM_SECTIONS.PERSONAL]: [
        {
            name: "last_name",
            label: "Last Name",
            type: "text",
            required: true,
            placeholder: "Enter your last name",
        },
        {
            name: "first_name",
            label: "First Name",
            type: "text",
            required: true,
            placeholder: "Enter your first name",
        },
        {
            name: "middle_name",
            label: "Middle Name",
            type: "text",
            required: false,
            placeholder: "Enter your middle name",
        },
        {
            name: "suffix",
            label: "Suffix",
            type: "select",
            options: ["", "None", "Jr", "Sr", "I", "II", "III", "IV"],
            defaultValue: "",
            required: false,
            placeholder: "Select suffix",
        },
        {
            name: "gender",
            label: "Gender",
            type: "select",
            options: ["", "Male", "Female"],
            defaultValue: "",
            required: true,
            placeholder: "Select gender",
        },
        {
            name: "age",
            label: "Age",
            type: "number",
            required: true,
            placeholder: "Enter your age",
        },
        {
            name: "birthdate",
            label: "Birthdate",
            type: "date",
            required: true,
            placeholder: "MM/DD/YYYY",
        },
        {
            name: "birthplace",
            label: "Birthplace",
            type: "text",
            required: true,
            placeholder: "Enter your birthplace",
        },
        {
            name: "home_address",
            label: "Home Address",
            type: "text",
            required: true,
            placeholder: "Enter your home address",
        },
        {
            name: "subdivision",
            label: "Village/Subdivision",
            type: "text",
            required: false,
            placeholder: "Enter village/subdivision",
        },
        {
            name: "barangay",
            label: "Barangay",
            type: "text",
            required: true,
            placeholder: "Enter barangay",
        },
        {
            name: "city",
            label: "City/Municipality",
            type: "text",
            required: true,
            placeholder: "Enter city/municipality",
        },
        {
            name: "zip_code",
            label: "Zipcode",
            type: "text",
            required: true,
            placeholder: "Enter zipcode",
        },
        {
            name: "contact_number",
            label: "Personal Contact",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
        },
        {
            name: "secondary_contact",
            label: "Secondary Contact",
            type: "text",
            required: false,
            placeholder: "e.g., 09123456789",
        },
        {
            name: "religion",
            label: "Religion",
            type: "text",
            required: true,
            placeholder: "Enter your religion",
        },
        {
            name: "civil_status",
            label: "Civil Status",
            type: "text",
            required: true,
            placeholder: "e.g., Single, Married",
        },
        {
            name: "facebook",
            label: "Facebook",
            type: "text",
            required: true,
            placeholder: "Enter your Facebook profile name",
        },
        {
            name: "email",
            label: "Email Address",
            type: "email",
            required: true,
            placeholder: "example@gmail.com",
        },
    ],
    [FORM_SECTIONS.EDUCATION]: [
        {
            name: "previous_school",
            label: "Last School Attended",
            type: "text",
            required: true,
            placeholder: "Enter name of school",
        },
        {
            name: "previous_location",
            label: "Location",
            type: "text",
            required: true,
            placeholder: "Enter school location",
        },
        {
            name: "previous_honor",
            label: "Honor Award",
            type: "text",
            required: false,
            placeholder: "e.g., With Honors, High Honors",
        },
        {
            name: "previous_gwa",
            label: "GWA",
            type: "text",
            required: true,
            placeholder: "Enter GWA",
        },
        {
            name: "previous_course",
            label: "Track",
            type: "text",
            required: false,
            placeholder: "e.g., STEM, ABM, HUMSS",
        },
        {
            name: "incoming_grade",
            label: "Incoming Grade/Year Level",
            type: "select",
            options: ["Select", "JHS", "SHS", "College", "Vocational"],
            defaultValue: "College",
            required: true,
            placeholder: "Select grade/year level",
        },
        {
            name: "present_school",
            label: "College/University",
            type: "select",
            options: [{ key: 0, name: "" }],
            defaultValue: "",
            required: true,
            placeholder: "Select school",
        },
        {
            name: "present_location",
            label: "Location",
            type: "text",
            required: true,
            placeholder: "Enter school location",
        },
        {
            name: "present_course1",
            label: "Course 1",
            type: "select",
            options: [{ key: 0, name: "" }],
            defaultValue: "",
            required: true,
            placeholder: "Select course",
        },
        {
            name: "present_course2",
            label: "Course 2",
            type: "select",
            options: [{ key: 0, name: "" }],
            defaultValue: "",
            required: false,
            placeholder: "Select course (optional)",
        },
        {
            name: "year_level",
            label: "Year Level",
            type: "select",
            options: [
                { value: "", name: "" },
                { value: 2, name: "2nd Year" },
                { value: 3, name: "3rd Year" },
                { value: 4, name: "4th Year" },
                { value: 5, name: "5th Year" },
            ],
            defaultValue: "",
            required: true,
            placeholder: "Select year level",
        },
    ],
    [FORM_SECTIONS.FAMILY]: [
        // Father's information
        {
            name: "father_name",
            label: "Name of Father",
            type: "text",
            required: true,
            placeholder: "Enter father's full name",
        },
        {
            name: "father_age",
            label: "Age",
            type: "number",
            required: true,
            placeholder: "Enter age",
        },
        {
            name: "father_education",
            label: "Educational Attainment",
            type: "text",
            required: true,
            placeholder: "e.g., College Graduate, High School",
        },
        {
            name: "father_occupation",
            label: "Occupation",
            type: "text",
            required: true,
            placeholder: "Enter occupation",
        },
        {
            name: "father_income",
            label: "Monthly Income",
            type: "number",
            required: true,
            placeholder: "Enter monthly income",
        },
        {
            name: "father_contact",
            label: "Contact Number",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
        },
        // Mother's information
        {
            name: "mother_name",
            label: "Name of Mother",
            type: "text",
            required: true,
            placeholder: "Enter mother's full name",
        },
        {
            name: "mother_age",
            label: "Age",
            type: "number",
            required: true,
            placeholder: "Enter age",
        },
        {
            name: "mother_education",
            label: "Educational Attainment",
            type: "text",
            required: true,
            placeholder: "e.g., College Graduate, High School",
        },
        {
            name: "mother_occupation",
            label: "Occupation",
            type: "text",
            required: true,
            placeholder: "Enter occupation",
        },
        {
            name: "mother_income",
            label: "Monthly Income",
            type: "number",
            required: true,
            placeholder: "Enter monthly income",
        },
        {
            name: "mother_contact",
            label: "Contact Number",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
        },
        // Guardian's information
        {
            name: "guardian_name",
            label: "Guardian Name",
            type: "text",
            required: false,
            placeholder: "Enter guardian's full name (if applicable)",
        },
        {
            name: "guardian_age",
            label: "Age",
            type: "text",
            required: false,
            placeholder: "Enter age",
        },
        {
            name: "guardian_education",
            label: "Educational Attainment",
            type: "text",
            required: false,
            placeholder: "e.g., College Graduate, High School",
        },
        {
            name: "guardian_occupation",
            label: "Occupation",
            type: "text",
            required: false,
            placeholder: "Enter occupation",
        },
        {
            name: "guardian_income",
            label: "Monthly Income",
            type: "text",
            required: false,
            placeholder: "Enter monthly income",
        },
        {
            name: "guardian_contact",
            label: "Contact Number",
            type: "text",
            required: false,
            placeholder: "e.g., 09123456789",
        },
    ],
    [FORM_SECTIONS.CONTACT_PERSON]: [
        {
            name: "emergency_contact_name",
            label: "Name",
            type: "text",
            required: true,
            placeholder: "Enter emergency contact name",
        },
        {
            name: "emergency_contact_relationship",
            label: "Relationship",
            type: "text",
            required: true,
            placeholder: "e.g., Father, Mother, Sibling",
        },
        // Aunt, Uncle, Sibling
        {
            name: "emergency_contact_address",
            label: "Address",
            type: "text",
            required: true,
            placeholder: "Enter complete address",
        },
        {
            name: "emergency_contact_number",
            label: "Contact Number",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
        },
    ],
    [FORM_SECTIONS.OTHER_INFORMATION]: [
        {
            name: "expectation",
            label: "What is your expectation from Tzu Chi Foundation?",
            type: "textarea",
            required: true,
            placeholder: "Share your expectations and goals...",
        },
    ],
};

export default formConfig;
