import FORM_SECTIONS from "../application/formSections";

const formConfig = {
    [FORM_SECTIONS.APPLICATION]: [
        {
            name: "school_year",
            label: "School Year",
            type: "text",
            required: true,
            placeholder: "e.g., 2024-2025",
            validate: "numbersOnly",
        },
        // { name: "caseNo", label: "Case Number", type: "text", required: true },
    ],
    [FORM_SECTIONS.PERSONAL]: [
        {
            name: "last_name",
            label: "Last Name",
            type: "text",
            required: true,
            placeholder: "Enter your last name",
            validate: "lettersOnly",
        },
        {
            name: "first_name",
            label: "First Name",
            type: "text",
            required: true,
            placeholder: "Enter your first name",
            validate: "lettersOnly",
        },
        {
            name: "middle_name",
            label: "Middle Name",
            type: "text",
            required: false,
            placeholder: "Enter your middle name",
            validate: "lettersOnly",
        },
        {
            name: "suffix",
            label: "Suffix",
            type: "select",
            options: ["", "None", "Jr", "Sr", "I", "II", "III", "IV"],
            defaultValue: "",
            required: false,
            placeholder: "Select suffix",
        },
        {
            name: "gender",
            label: "Gender",
            type: "select",
            options: ["", "Male", "Female"],
            defaultValue: "",
            required: true,
            placeholder: "Select gender",
        },
        // {
        //     name: "age",
        //     label: "Age",
        //     type: "text",
        //     required: true,
        //     placeholder: "Enter your age",
        //     validate: "numbersOnly",
        // },
        {
            name: "birthdate",
            label: "Birthdate",
            type: "date",
            required: true,
            placeholder: "MM/DD/YYYY",
        },
        {
            name: "birthplace",
            label: "Birthplace",
            type: "text",
            required: true,
            placeholder: "Enter your birthplace",
            validate: "lettersNumbers",
        },
        {
            name: "home_address",
            label: "Home Address",
            type: "text",
            required: true,
            placeholder: "Enter your home address",
            validate: "lettersNumbers",
        },
        {
            name: "subdivision",
            label: "Village/Subdivision",
            type: "text",
            required: false,
            placeholder: "Enter village/subdivision",
            validate: "lettersNumbers",
        },
        {
            name: "barangay",
            label: "Barangay",
            type: "text",
            required: true,
            placeholder: "Enter barangay",
            validate: "lettersOnly",
        },
        {
            name: "city",
            label: "City/Municipality",
            type: "text",
            required: true,
            placeholder: "Enter city/municipality",
            validate: "lettersOnly",
        },
        {
            name: "zip_code",
            label: "Zipcode",
            type: "text",
            required: true,
            placeholder: "Enter zipcode",
            validate: "numbersOnly",
        },
        {
            name: "contact_number",
            label: "Personal Contact",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
            validate: "numbersOnly",
        },
        {
            name: "secondary_contact",
            label: "Secondary Contact",
            type: "text",
            required: false,
            placeholder: "e.g., 09123456789",
            validate: "numbersOnly",
        },
        {
            name: "religion",
            label: "Religion",
            type: "text",
            required: true,
            placeholder: "Enter your religion",
            validate: "lettersOnly",
        },
        {
            name: "civil_status",
            label: "Civil Status",
            type: "text",
            required: true,
            placeholder: "e.g., Single, Married",
            validate: "lettersOnly",
        },
        {
            name: "facebook",
            label: "Facebook Link",
            type: "text",
            required: true,
            placeholder: "Enter your Facebook profile name",
            validate: "urlOnly",
        },
        {
            name: "email",
            label: "Email Address",
            type: "email",
            required: true,
            placeholder: "example@gmail.com",
        },
    ],
    [FORM_SECTIONS.EDUCATION]: [
        {
            name: "previous_school",
            label: "Last School Attended",
            type: "text",
            required: true,
            placeholder: "Enter name of school",
            validate: "lettersOnly",
        },
        {
            name: "previous_location",
            label: "Location",
            type: "text",
            required: true,
            placeholder: "Enter school location",
            validate: "lettersNumbers",
        },
        {
            name: "previous_honor",
            label: "Honor Award",
            type: "text",
            required: false,
            placeholder: "e.g., With Honors, High Honors",
            validate: "lettersOnly",
        },
        {
            name: "previous_gwa",
            label: "GWA",
            type: "text",
            required: true,
            placeholder: "Enter GWA",
            validate: "numbersOnly",
        },
        {
            name: "previous_course",
            label: "Track",
            type: "text",
            required: true,
            placeholder: "e.g., STEM, ABM, HUMSS",
            validate: "lettersOnly",
        },
        {
            name: "incoming_grade",
            label: "Incoming Grade/Year Level",
            type: "select",
            options: ["Select", "JHS", "SHS", "College", "Vocational"],
            defaultValue: "College",
            required: true,
            placeholder: "Select grade/year level",
        },
        {
            name: "present_school",
            label: "College/University",
            type: "select",
            options: [{ key: 0, name: "" }],
            defaultValue: "",
            required: true,
            placeholder: "Select school",
        },
        {
            name: "present_location",
            label: "Location",
            type: "text",
            required: true,
            placeholder: "Enter school location",
            validate: "lettersNumbers",
        },
        {
            name: "present_course1",
            label: "Course 1",
            type: "select",
            options: [{ key: 0, name: "" }],
            defaultValue: "",
            required: true,
            placeholder: "Select course",
        },
        {
            name: "present_course2",
            label: "Course 2",
            type: "select",
            options: [{ key: 0, name: "" }],
            defaultValue: "",
            required: false,
            placeholder: "Select course (optional)",
        },
        {
            name: "year_level",
            label: "Year Level",
            type: "select",
            options: [
                { value: "", name: "" },
                { value: 2, name: "2nd Year" },
                { value: 3, name: "3rd Year" },
                { value: 4, name: "4th Year" },
                { value: 5, name: "5th Year" },
            ],
            defaultValue: "",
            required: true,
            placeholder: "Select year level",
        },
    ],
    [FORM_SECTIONS.FAMILY]: [
        // Father's information
        {
            name: "father_name",
            label: "Name of Father",
            type: "text",
            required: true,
            placeholder: "Enter father's full name",
            validate: "lettersOnly",
        },
        {
            name: "father_age",
            label: "Age",
            type: "text",
            required: true,
            placeholder: "Enter age",
            validate: "numbersOnly",
        },
        {
            name: "father_education",
            label: "Educational Attainment",
            type: "text",
            required: true,
            placeholder: "e.g., College Graduate, High School",
            validate: "lettersOnly",
        },
        {
            name: "father_occupation",
            label: "Occupation",
            type: "text",
            required: true,
            placeholder: "Enter occupation",
            validate: "lettersOnly",
        },
        {
            name: "father_income",
            label: "Monthly Income",
            type: "text",
            required: true,
            placeholder: "Enter monthly income",
            validate: "numbersOnly",
        },
        {
            name: "father_contact",
            label: "Contact Number",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
            validate: "numbersOnly",
        },
        // Mother's information
        {
            name: "mother_name",
            label: "Name of Mother",
            type: "text",
            required: true,
            placeholder: "Enter mother's full name",
            validate: "lettersOnly",
        },
        {
            name: "mother_age",
            label: "Age",
            type: "text",
            required: true,
            placeholder: "Enter age",
            validate: "numbersOnly",
        },
        {
            name: "mother_education",
            label: "Educational Attainment",
            type: "text",
            required: true,
            placeholder: "e.g., College Graduate, High School",
            validate: "lettersOnly",
        },
        {
            name: "mother_occupation",
            label: "Occupation",
            type: "text",
            required: true,
            placeholder: "Enter occupation",
            validate: "lettersOnly",
        },
        {
            name: "mother_income",
            label: "Monthly Income",
            type: "text",
            required: true,
            placeholder: "Enter monthly income",
            validate: "numbersOnly",
        },
        {
            name: "mother_contact",
            label: "Contact Number",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
            validate: "numbersOnly",
        },
        // Guardian's information
        {
            name: "guardian_name",
            label: "Guardian Name",
            type: "text",
            required: false,
            placeholder: "Enter guardian's full name (if applicable)",
            validate: "lettersOnly",
        },
        {
            name: "guardian_age",
            label: "Age",
            type: "text",
            required: false,
            placeholder: "Enter age",
            validate: "numbersOnly",
        },
        {
            name: "guardian_education",
            label: "Educational Attainment",
            type: "text",
            required: false,
            placeholder: "e.g., College Graduate, High School",
            validate: "lettersOnly",
        },
        {
            name: "guardian_occupation",
            label: "Occupation",
            type: "text",
            required: false,
            placeholder: "Enter occupation",
            validate: "lettersOnly",
        },
        {
            name: "guardian_income",
            label: "Monthly Income",
            type: "text",
            required: false,
            placeholder: "Enter monthly income",
            validate: "numbersOnly",
        },
        {
            name: "guardian_contact",
            label: "Contact Number",
            type: "text",
            required: false,
            placeholder: "e.g., 09123456789",
            validate: "numbersOnly",
        },
    ],
    [FORM_SECTIONS.CONTACT_PERSON]: [
        {
            name: "emergency_contact_name",
            label: "Name",
            type: "text",
            required: true,
            placeholder: "Enter emergency contact name",
            validate: "lettersOnly",
        },
        {
            name: "emergency_contact_relationship",
            label: "Relationship",
            type: "text",
            required: true,
            placeholder: "e.g., Father, Mother, Sibling",
            validate: "lettersOnly",
        },
        // Aunt, Uncle, Sibling
        {
            name: "emergency_contact_address",
            label: "Address",
            type: "text",
            required: true,
            placeholder: "Enter complete address",
            validate: "lettersNumbers",
        },
        {
            name: "emergency_contact_number",
            label: "Contact Number",
            type: "text",
            required: true,
            placeholder: "e.g., 09123456789",
            validate: "numbersOnly",
        },
    ],
    [FORM_SECTIONS.OTHER_INFORMATION]: [
        {
            name: "expectation",
            label: "What is your expectation from Tzu Chi Foundation?",
            type: "textarea",
            required: true,
            placeholder: "Share your expectations and goals...",
        },
    ],
};

export default formConfig;
