<?php

namespace App\Constants;

class Action
{
    public const CREATE = 'CREATE';
    public const UPDATE = 'UPDATE';
    public const DELETE = 'DELETE';
    public const APPROVE = 'APPROVE';
    public const REJECT = 'REJECT';
    public const UPLOAD = 'UPLOAD';
    public const DOCUMENT_SUBMITTED = 'DOCUMENT_SUBMIT';
    public const DOCUMENT_UPDATED = 'DOCUMENT_UPDATE';
    public const EVENT_JOINED = 'EVENT_JOIN';
    public const EVENT_CANCELED = 'EVENT_CANCEL';
    public const APPLICATION_SUBMITTED = 'APPLICATION_SUBMIT';
    public const RENEWAL_APPLICATION_SUBMITTED = 'RENEWAL_APPLICATION_SUBMIT';
    public const RENEWAL_APPLICATION_RESUBMITTED = 'RENEWAL_APPLICATION_RESUBMIT';
    public const APPLICATION_APPROVED = 'APPLICATION_APPROVE';
    public const APPLICATION_REJECTED = 'APPLICATION_REJECT';
    public const FORM_SUBMITTED = 'FORM_SUBMIT';
    public const SCHOOL_CREATED = 'SCHOOL_CREATE';
    public const SCHOOL_UPDATED = 'SCHOOL_UPDATE';
    public const SCHOOL_DELETED = 'SCHOOL_DELETE';
    public const COURSE_CREATED = 'COURSE_CREATE';
    public const COURSE_UPDATED = 'COURSE_UPDATE';
    public const COURSE_DELETED = 'COURSE_DELETE';
    public const STRAND_CREATE = 'STRAND_CREATE';
    public const STRAND_UPDATE = 'STRAND_UPDATE';
    public const STRAND_DELETE = 'STRAND_DELETE';
    public const QUALIFICATION_CREATE = 'QUALIFICATION_CREATE';
    public const QUALIFICATION_UPDATE = 'QUALIFICATION_UPDATE';
    public const QUALIFICATION_DELETE = 'QUALIFICATION_DELETE';
    public const REQUIREMENT_CREATE = 'REQUIREMENT_CREATE';
    public const REQUIREMENT_UPDATE = 'REQUIREMENT_UPDATE';
    public const REQUIREMENT_DELETE = 'REQUIREMENT_DELETE';
    public const PROCEDURE_CREATE = 'PROCEDURE_CREATE';
    public const PROCEDURE_UPDATE = 'PROCEDURE_UPDATE';
    public const PROCEDURE_DELETE = 'PROCEDURE_DELETE';
    public const INSTRUCTION_CREATE = 'INSTRUCTION_CREATE';
    public const INSTRUCTION_UPDATE = 'INSTRUCTION_UPDATE';
    public const INSTRUCTION_DELETE = 'INSTRUCTION_DELETE';
    public const APPLICATION_PERIOD_CREATE = 'APPLICATION_PERIOD_CREATE';
    public const APPLICATION_PERIOD_UPDATE = 'APPLICATION_PERIOD_UPDATE';
    public const APPLICATION_PERIOD_DELETE = 'APPLICATION_PERIOD_DELETE';
}
